### ISSUE TITLE
EL codigo no se ajusta a los requerimientos

### ISSUE THREAD

**Issue by evolentini** [nicolascecchi/tp2-iot-vA#1]
No hay un requerimiento que pida obtener todos los elementos de la lista, solo las claves ordenadas.

https://github.com/nicolascecchi/tp2-iot-vA/blob/0e9849ad0bb07c539be2583f01689d7d6e51e74c/utils/clase_diccionario.py#L12-L13

**Comment by nicolascecchi** [comment]
Se elimina el método "ver_dic" por "get_claves_ordenadas".
