### ISSUE TITLE
La prueba no verifica el requisito

### ISSUE THREAD

**Issue by evolentini** [nicolascecchi/tp2-iot-vA#2]
El requisito es que no se puedan agregar claves que no sean del tipo string y la prueba desarrolla no prueba nada. Lo que se debe hacer es intentar agregar un dato con una clave que no sea un string y esperar un error o excepción.

https://github.com/nicolascecchi/tp2-iot-vA/blob/0e9849ad0bb07c539be2583f01689d7d6e51e74c/test/test_tp2py.py#L45-L49

**Comment by nicolascecchi** [comment]
Se modifica el test y agrega  "assert isinstance(key, str)" en el método para agregar elementos.
