### ISSUE TITLE
Corregir los textos de las pruebas

### ISSUE THREAD

**Issue by evolentini** [nicolascecchi/tp2-iot-vA#3]
En esta prueba los textos dicen justo lo contrario de los que se está haciendo: recuperar la cantidad de elementos

https://github.com/nicolascecchi/tp2-iot-vA/blob/0e9849ad0bb07c539be2583f01689d7d6e51e74c/test/test_tp2py.py#L25-L29

**Comment by nicolascecchi** [comment]
Efectivamente dice lo contrario, pero lo puse porque cuando estaba probando vi que ese es el mensaje que sale cuando la assertion tira el error. Es decir, si la prueba falla, es el mensaje que se muestra.

**Comment by evolentini** [comment]
En ese caso el texto debería ser algo como "No se recuperó la cantidad esperada de elementos"
